name = "SFTPClient"
uuid = "6f0ef2a9-1531-47bc-8c87-f4ce50005508"
authors = ["Erik Stensmo "]
version = "0.3.7"

[deps]
ArgTools = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
NetworkOptions = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
ArgTools = "1.1"
LibCURL = "0.6"
NetworkOptions = "1.2"
Downloads = "1.4.3"
URIs = "1.5.0"
julia = "1.9"
CSV = "0.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test"]
